{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gg-core.serviceAccountName" . }}
  labels:
    {{- include "gg-core.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
